@hostname = localhost 
@port = 3200 
@host = {{hostname}}:{{port}} 
@entity = login 
@contentType = application/json


### 
POST http://{{host}}/{{entity}}/exists HTTP/1.1 
content-type: {{contentType}}

{
    "email": "Testing.ode@outlook.com"
}

### 
POST http://{{host}}/{{entity}}/ HTTP/1.1 
content-type: {{contentType}}

{
    "email": "Testing.node@outlook.com",
    "password": "222211"
}


### 
POST http://{{host}}/{{entity}}/validToken HTTP/1.1 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7ImlkIjoxfSwiaWF0IjoxNjcwMTc0NzM1LCJleHAiOjE2NzAyMTA3MzV9.AnKB1EgMsn5kIpzoQd3HAfejZCk2PnCMg3u5LJYO5to

### 
POST http://{{host}}/{{entity}}/reset HTTP/1.1 
content-type: {{contentType}}

{
    "id": "1",
    "password": "123123"
}

### 
POST http://{{host}}/{{entity}}/resetEmail HTTP/1.1 
content-type: {{contentType}}

{
    "id": 1
}
