@hostname = localhost 
@port = 3200 
@host = {{hostname}}:{{port}} 
@entity = login 
@contentType = application/json


### 
POST http://{{host}}/{{entity}}/exists HTTP/1.1 
content-type: {{contentType}}

{
    "mail": "Testing.node@outlook.com"
}

### 
POST http://{{host}}/{{entity}}/ HTTP/1.1 
content-type: {{contentType}}

{
    "mail": "Testing.node@outlook.com",
    "password": "1231321"
}


### 
POST http://{{host}}/{{entity}}/validToken HTTP/1.1 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7ImlkIjoxLCJuYW1lIjoiQWRtaW5pc3RyYSBEb3IiLCJyb2wiOjB9LCJpYXQiOjE2NjU4NzExNTIsImV4cCI6MTY2NTkwNzE1Mn0.iUBy3WDpKtvqnaXqdhRHFs86-FEfmYliO7-0gqGrnEA
