@hostname = localhost 
@port = 3200 
@host = {{hostname}}:{{port}} 
@entity = milestone 
@contentType = application/json

### 
GET http://{{host}}/{{entity}} HTTP/1.1

### 
GET http://{{host}}/{{entity}}/26 HTTP/1.1

### 
POST http://{{host}}/{{entity}} HTTP/1.1 
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InJvbCI6MywiaWQiOjF9LCJpYXQiOjE2NjU1OTUyNDgsImV4cCI6MTY2NTYzMTI0OH0.GFm1Hh7O8zYgS5bjn5a56zNe5LybvLMPSzYHYfSAKck

{
    "title": "Some milestone",
    "date": "2022-07",
    "description":"Some milestone", 
    "image":"data:image/jpeg;base64,/9j/", 
    "userId": "1"
}

### 
PUT http://{{host}}/{{entity}}/2 HTTP/1.1 
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InJvbCI6MywiaWQiOjF9LCJpYXQiOjE2NjU1OTUyNDgsImV4cCI6MTY2NTYzMTI0OH0.GFm1Hh7O8zYgS5bjn5a56zNe5LybvLMPSzYHYfSAKck

{
    "title": "Some updated milestonwe",
    "date": "Setiembre 2022",
    "description":"Some updated milestone", 
    "image":"data:image/jpeg;base64,/9j/"
}

### 
DELETE http://{{host}}/{{entity}}/1 HTTP/1.1
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InJvbCI6MywiaWQiOjF9LCJpYXQiOjE2NjU1OTUyNDgsImV4cCI6MTY2NTYzMTI0OH0.GFm1Hh7O8zYgS5bjn5a56zNe5LybvLMPSzYHYfSAKck

{
    "userId": "1"
}