@hostname = localhost 
@port = 3200 
@host = {{hostname}}:{{port}} 
@entity = pin 
@contentType = application/json

### 
GET http://{{host}}/{{entity}} HTTP/1.1

### 
GET http://{{host}}/{{entity}}/2 HTTP/1.1

### 
POST http://{{host}}/{{entity}} HTTP/1.1 
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InJvbCI6MywiaWQiOjF9LCJpYXQiOjE2NjU3NzQ2NTksImV4cCI6MTY2NTgxMDY1OX0.C3VqLx7Vqcv67hXw51bGU2yxIotRje6ZPcuguWSk9JM

{
    "name": "Asada la prueba de node",
    "province":"Limón", 
    "canton":"Pococí" , 
    "district":"Guápiles", 
    "position":"[11.18,-83.74]",
    "userId": "1"
}

### 
PUT http://{{host}}/{{entity}}/1 HTTP/1.1 
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InJvbCI6MywiaWQiOjF9LCJpYXQiOjE2NjU3MDM3ODUsImV4cCI6MTY2NTczOTc4NX0.GbdQ865-HVeOOgvxQ9MnjNn8uGZIGXKvbCjBYrmEIdE

{
    "name": "Asada la prueba de node",
    "province":"Limón", 
    "canton":"Pococí" , 
    "district":"Guápiles", 
    "position":"[10.18,-83.74]"
}

### 
DELETE http://{{host}}/{{entity}}/2 HTTP/1.1
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InJvbCI6MywiaWQiOjF9LCJpYXQiOjE2NjU3MDM3ODUsImV4cCI6MTY2NTczOTc4NX0.GbdQ865-HVeOOgvxQ9MnjNn8uGZIGXKvbCjBYrmEIdE

{
    "userId": "1"
}