@hostname = localhost 
@port = 3200 
@host = {{hostname}}:{{port}} 
@entity = pin 
@contentType = application/json

### 
GET http://{{host}}/{{entity}} HTTP/1.1

### 
GET http://{{host}}/{{entity}}/1 HTTP/1.1

### 
POST http://{{host}}/{{entity}} HTTP/1.1 
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InJvbCI6MH0sImlhdCI6MTY2NDgyMzkwMywiZXhwIjoxNjY0ODU5OTAzfQ.XBmvVjmIwnJuLexmMyK8q1VFf0JNpE4g1juIKtBXqnE

{
    "title": "Some service",
    "description":"Some description", 
    "details":"[]" , 
    "image":"", 
    "thumbnail":"",
    "contactId": "1",
    "userId": "1"
}

### 
PUT http://{{host}}/{{entity}}/5 HTTP/1.1 
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InJvbCI6MH0sImlhdCI6MTY2NDgyMzkwMywiZXhwIjoxNjY0ODU5OTAzfQ.XBmvVjmIwnJuLexmMyK8q1VFf0JNpE4g1juIKtBXqnE

{
    "title": "Some updated service",
    "description":"Some updated description", 
    "details":"[]" , 
    "image":"", 
    "thumbnail":"",
    "contactId": "1",
    "userId": "1"
}


### 
DELETE http://{{host}}/{{entity}}/1 HTTP/1.1
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InJvbCI6MH0sImlhdCI6MTY2NDgyMzkwMywiZXhwIjoxNjY0ODU5OTAzfQ.XBmvVjmIwnJuLexmMyK8q1VFf0JNpE4g1juIKtBXqnE

{
    "userId": "1"
}