@hostname = localhost 
@port = 3200 
@host = {{hostname}}:{{port}} 
@entity = service 
@contentType = application/json

### 
GET http://{{host}}/{{entity}} HTTP/1.1

### 
GET http://{{host}}/{{entity}}/1 HTTP/1.1

### 
POST http://{{host}}/{{entity}} HTTP/1.1 
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InVzZXJJZCI6MSwicm9sIjozfSwiaWF0IjoxNjY0ODM0NTkyLCJleHAiOjE2NjQ4NzA1OTJ9.sGvuXZrJcbQtfxKZJ3h7FJqIIHPD2-03-DzHxMzl10U

{
    "title": "Some service",
    "description":"Some description", 
    "details":"[]" , 
    "image":"", 
    "thumbnail":"",
    "contactId": "1",
    "userId": "1"
}

### 
PUT http://{{host}}/{{entity}}/5 HTTP/1.1 
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InVzZXJJZCI6MSwicm9sIjozfSwiaWF0IjoxNjY0ODM0NTkyLCJleHAiOjE2NjQ4NzA1OTJ9.sGvuXZrJcbQtfxKZJ3h7FJqIIHPD2-03-DzHxMzl10U

{
    "title": "Some updated service",
    "description":"Some updated description", 
    "details":"[]" , 
    "image":"", 
    "thumbnail":"",
    "contactId": "1",
    "userId": "1"
}


### 
DELETE http://{{host}}/{{entity}}/1 HTTP/1.1
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InVzZXJJZCI6MSwicm9sIjozfSwiaWF0IjoxNjY0ODM0NTkyLCJleHAiOjE2NjQ4NzA1OTJ9.sGvuXZrJcbQtfxKZJ3h7FJqIIHPD2-03-DzHxMzl10U

{
    "userId": "1"
}