@hostname = localhost 
@port = 3200 
@host = {{hostname}}:{{port}} 
@entity = test 
@contentType = application/json

### 
GET http://{{host}}/{{entity}} HTTP/1.1

### 
GET http://{{host}}/{{entity}}/1 HTTP/1.1

### 
POST http://{{host}}/{{entity}} HTTP/1.1 
content-type: {{contentType}}
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7InJvbCI6MH0sImlhdCI6MTY2NDgyMzkwMywiZXhwIjoxNjY0ODU5OTAzfQ.XBmvVjmIwnJuLexmMyK8q1VFf0JNpE4g1juIKtBXqnE

{
    "name": "Prueba as"
}

### 
PUT http://{{host}}/{{entity}}/4 HTTP/1.1 
content-type: {{contentType}}

{
    "name": "Sirviendo"
}

### 
DELETE http://{{host}}/{{entity}}/2 HTTP/1.1