@hostname = localhost 
@port = 3200 
@host = {{hostname}}:{{port}} 
@entity = test 
@contentType = application/json

### 
GET http://{{host}}/{{entity}} HTTP/1.1

### 
GET http://{{host}}/{{entity}}/1 HTTP/1.1

### 
POST http://{{host}}/{{entity}} HTTP/1.1 
content-type: {{contentType}}

{
    "name": "Prueba as111111111111111111"
}

### 
PUT http://{{host}}/{{entity}}/4 HTTP/1.1 
content-type: {{contentType}}

{
    "name": "Sirviendo"
}

### 
DELETE http://{{host}}/{{entity}}/2 HTTP/1.1